security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\SecUser:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\SecUser
                property: email
    #        app_ad_provider:
    #            id: App\Security\AdUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            custom_authenticators:
                - App\Security\AzureAuthenticator
            lazy: true
            provider: app_user_provider

            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
            #                password_parameter: password
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_projekte_uebersicht

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                #always_remember_me: true
        # Easy way to control access for large sections of your site
        #Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
    role_hierarchy:
        # Der Teamleiter "erbt" die Rechte von Techniker und Logistiker
        ROLE_TEAMLEAD: [ ROLE_TECH, ROLE_LOGISTIC ]

        # Der Admin erbt alles vom Teamleiter (und damit auch Tech/Logistik)
        ROLE_ADMIN: [ ROLE_TEAMLEAD ]