<?php

declare( strict_types=1 );

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423083900 extends
    AbstractMigration
{

    public function getDescription(): string
    {
        return '';
    }

    public function up( Schema $schema ): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql( "INSERT INTO `flaggenstaaten` (`id`, `amtliche_kurzform`, `amtliche_vollform`, `kuerzel`, `flagge`) VALUES
                                            (1, 'Deutschland', 'Bundesrepublik Deutschland', 'de', 'de.svg'),
                                            (3, 'Antigua und Barbuda', 'Antigua und Barbuda', 'ag', 'ag.svg'),
                                            (4, 'Bahamas', 'das Commonwealth der Bahamas', 'bs', 'bs.svg'),
                                            (5, 'Bermuda', 'die Bermudas', 'bm', 'bm.svg'),
                                            (6, 'China', 'die Volksrepublik China', 'cn', 'cn.svg'),
                                            (7, 'Dänemark', 'das Knigreich Dänemark', 'dk', 'dk.svg'),
                                            (8, 'Frankreich', 'die Franzsische Republik', 'fr', 'fr.svg'),
                                            (9, 'Gibraltar', 'die Kolonie Gibraltar', 'gi', 'gi.svg'),
                                            (10, 'Griechenland', 'die Hellenische Republik', 'gr', 'gr.svg'),
                                            (11, 'Guyana', 'die Kooperative Republik Guyana', 'gy', 'gy.svg'),
                                            (12, 'Insel Man', 'die Insel Man', 'im', 'im.svg'),
                                            (13, 'Kanada', 'Kanada', 'ca', 'ca.svg'),
                                            (14, 'Jamaika', 'Jamaika', 'jm', 'jm.svg'),
                                            (15, 'Lettland', 'die Republik Lettland', 'lv', 'lv.svg'),
                                            (16, 'Liberia', 'die Republik Liberia', 'lr', 'lr.svg'),
                                            (17, 'Litauen', 'die Republik Litauen', 'lt', 'lt.svg'),
                                            (18, 'Luxemburg', 'das Groherzogtum Luxemburg', 'lu', 'lu.svg'),
                                            (19, 'Malta', 'die Republik Malta', 'mt', 'mt.svg'),
                                            (20, 'Marshallinseln', 'die Republik Marshallinseln', 'mh', 'mh.svg'),
                                            (21, 'Neuseeland', 'Neuseeland', 'nz', 'nz.svg'),
                                            (22, 'Niederlande', 'das Knigreich der Niederlande', 'nl', 'nl.svg'),
                                            (23, 'Panama', 'die Republik Panama', 'pa', 'pa.svg'),
                                            (24, 'Polen', 'die Republik Polen', 'pl', 'pl.svg'),
                                            (25, 'Portugal', 'die Portugiesische Republik', 'pt', 'pt.svg'),
                                            (26, 'Rumnien', 'Rumnien', 'ro', '6909a3873a9bf.svg'),
                                            (27, 'San Marino', 'die Republik San Marino', 'sm', '697a14ad0878d.svg'),
                                            (28, 'Singapur', 'die Republik Singapur', 'sg', 'sg.svg'),
                                            (29, 'Spanien', 'das Knigreich Spanien', 'es', '68ff29f2e2d57.svg'),
                                            (30, 'Sri Lanka', 'die Demokratische Sozialistische Republik Sri Lanka', 'lk', '68e62acfd58a0.png'),
                                            (31, 'St. Vincent und die Grenadinen', 'St. Vincent und die Grenadinen', 'vc', '68e62b9b89312.png'),
                                            (32, 'Südafrika', 'die Republik Südafrika', 'za', '68e62aee24194.svg'),
                                            (33, 'Vereinigtes Königreich', 'das Vereinigte Königreich Grobritannien und Nordirland', 'gb', 'gb.svg'),
                                            (34, 'Vietnam', 'die Sozialistische Republik Vietnam', 'vn', '68e62c2c7200f.png'),
                                            (35, 'Zypern', 'die Republik Zypern', 'cy', '68e62c987c12e.svg'),
                                            (36, 'Belgien', 'Knigreich Belgien', 'be', 'be.svg'),
                                            (37, 'Italien', 'Italienische Republik', 'it', 'it.svg'),
                                            (39, 'Malaysia', 'das Königreich Malaysia', 'my', 'my.svg'),
                                            (40, 'Japan', 'Japan', 'jp', 'jp.svg'),
                                            (41, 'Türkei', 'Republik Türkei', 'tr', 'tr.svg'),
                                            (42, 'Adele Island', 'Adele Island', 'xd', 'xd.svg'),
                                            (44, 'Afghanistan', 'Afghanistan', 'af', 'af.svg'),
                                            (45, 'Aland Islands', 'Aland Islands', 'ax', 'ax.svg'),
                                            (46, 'Alaska', 'Alaska', 'xc', 'xc.svg'),
                                            (47, 'Albania', 'Albania', 'al', 'al.svg'),
                                            (48, 'Algeria', 'Algeria', 'dz', '68ff40a778a4a.svg'),
                                            (49, 'American Samoa', 'American Samoa', 'as', 'as.svg'),
                                            (50, 'Andorra', 'Andorra', 'ad', 'ad.svg'),
                                            (51, 'Angola', 'Angola', 'ao', 'ao.svg'),
                                            (52, 'Anguilla', 'Anguilla', 'ai', 'ai.svg'),
                                            (53, 'Antarctica', 'Antarctica', 'aq', 'aq.svg'),
                                            (54, 'Argentina', 'Argentina', 'ar', '68ca619e7674c.svg'),
                                            (55, 'Armenia', 'Armenia', 'am', 'am.svg'),
                                            (56, 'Aruba', 'Aruba', 'aw', 'aw.svg'),
                                            (57, 'Ascension Island', 'Ascension Island', 'xe', 'xe.svg'),
                                            (58, 'Australia', 'Australia', 'au', '68ca644433142.svg'),
                                            (59, 'Austria', 'Austria', 'at', 'at.svg'),
                                            (60, 'Azerbaijan', 'Azerbaijan', 'az', 'az.svg'),
                                            (61, 'Azores', 'Azores', 'xa', 'xa.svg'),
                                            (62, 'Bahrain', 'Bahrain', 'bh', 'bh.svg'),
                                            (63, 'Bangladesh', 'Bangladesh', 'bd', 'bd.svg'),
                                            (64, 'Barbados', 'Barbados', 'bb', 'bb.svg'),
                                            (65, 'Belarus', 'Belarus', 'by', 'by.svg'),
                                            (66, 'Belize', 'Belize', 'bz', 'bz.svg'),
                                            (67, 'Benin', 'Benin', 'bj', '6909a4465d37d.svg'),
                                            (68, 'Bhutan', 'Bhutan', 'bt', 'bt.svg'),
                                            (69, 'Bolivia', 'Bolivia', 'bo', 'bo.svg'),
                                            (70, 'Bonaire, Sint Eustat', 'Bonaire, Sint Eustatius and Saba', 'bq', 'bq.svg'),
                                            (71, 'Bosnia and Herzegovi', 'Bosnia and Herzegovina', 'ba', 'ba.svg'),
                                            (72, 'Botswana', 'Botswana', 'bw', 'bw.svg'),
                                            (73, 'Bouvet Island', 'Bouvet Island', 'bv', 'bv.svg'),
                                            (74, 'Brazil', 'Brazil', 'br', '69006fd55f487.svg'),
                                            (75, 'British Indian Ocean', 'British Indian Ocean Territory', 'io', 'io.svg'),
                                            (76, 'Brunei Darussalam', 'Brunei Darussalam', 'bn', 'bn.svg'),
                                            (77, 'Bulgaria', 'Bulgaria', 'bg', '68ff2c6f69068.webp'),
                                            (78, 'Burkina Faso', 'Burkina Faso', 'bf', 'bf.svg'),
                                            (79, 'Burundi', 'Burundi', 'bi', 'bi.svg'),
                                            (80, 'Cabo Verde', 'Cabo Verde', 'cv', 'cv.svg'),
                                            (81, 'Cambodia', 'Cambodia', 'kh', 'kh.svg'),
                                            (82, 'Cameroon', 'Cameroon', 'cm', 'cm.svg'),
                                            (83, 'Cayman Islands', 'Cayman Islands', 'ky', 'ky.svg'),
                                            (84, 'Central African Repu', 'Central African Republic', 'cf', 'cf.svg'),
                                            (85, 'Chad', 'Chad', 'td', 'td.svg'),
                                            (86, 'Chile', 'Chile', 'cl', 'cl.svg'),
                                            (87, 'Christmas Island', 'Christmas Island', 'cx', 'cx.svg'),
                                            (88, 'Cocos (Keeling) Isla', 'Cocos (Keeling) Islands', 'cc', 'cc.svg'),
                                            (89, 'Colombia', 'Colombia', 'co', 'co.svg'),
                                            (90, 'Comoros', 'Comoros', 'km', 'km.svg'),
                                            (91, 'Congo', 'Congo', 'cg', 'cg.svg'),
                                            (92, 'Congo (DR)', 'Congo (DR)', 'cd', 'cd.svg'),
                                            (93, 'Cook Islands', 'Cook Islands', 'ck', 'ck.svg'),
                                            (94, 'Costa Rica', 'Costa Rica', 'cr', 'cr.svg'),
                                            (95, 'Cote d\'Ivoire', 'Cote d\'Ivoire', 'ci', '68ff3f14e5c4c.png'),
                                            (96, 'Croatia', 'Croatia', 'hr', '6909a527bcaed.svg'),
                                            (97, 'Crozet Archipelago', 'Crozet Archipelago', 'xf', 'xf.svg'),
                                            (98, 'Cuba', 'Cuba', 'cu', 'cu.svg'),
                                            (99, 'Curacao', 'Curacao', 'cw', 'cw.svg'),
                                            (101, 'Czech Republic', 'Czech Republic', 'cz', 'cz.svg'),
                                            (102, 'Czechoslovakia', 'Czechoslovakia', 'cs', 'cs.svg'),
                                            (103, 'Djibouti', 'Djibouti', 'dj', '68ca669a70509.svg'),
                                            (104, 'Dominica', 'Dominica', 'dm', 'dm.svg'),
                                            (105, 'Dominican Republic', 'Dominican Republic', 'do', 'do.svg'),
                                            (106, 'East Timor', 'East Timor', 'tl', 'tl.svg'),
                                            (107, 'Ecuador', 'Ecuador', 'ec', 'ec.svg'),
                                            (108, 'Egypt', 'Egypt', 'eg', '68ff29bb282aa.svg'),
                                            (109, 'El Salvador', 'El Salvador', 'sv', 'sv.svg'),
                                            (110, 'Equatorial Guinea', 'Equatorial Guinea', 'gq', 'gq.svg'),
                                            (111, 'Eritrea', 'Eritrea', 'er', 'er.svg'),
                                            (112, 'Estonia', 'Estonia', 'ee', 'ee.svg'),
                                            (113, 'Ethiopia', 'Ethiopia', 'et', 'et.svg'),
                                            (114, 'Falkland Islands', 'Falkland Islands', 'fk', 'fk.svg'),
                                            (115, 'Faroe Islands', 'Faroe Islands', 'fo', 'fo.svg'),
                                            (116, 'Fiji', 'Fiji', 'fj', 'fj.svg'),
                                            (117, 'Finland', 'Finland', 'fi', 'fi.svg'),
                                            (118, 'French Guiana', 'French Guiana', 'gf', 'gf.svg'),
                                            (119, 'French Polynesia', 'French Polynesia', 'pf', 'pf.svg'),
                                            (120, 'French Southern Terr', 'French Southern Territories', 'tf', 'tf.svg'),
                                            (121, 'Gabon', 'Gabon', 'ga', 'ga.svg'),
                                            (122, 'Gambia', 'Gambia', 'gm', 'gm.svg'),
                                            (123, 'Georgia', 'Georgia', 'ge', '68ff2cb00e7df.svg'),
                                            (125, 'Ghana', 'Ghana', 'gh', '68ff3f4f23554.svg'),
                                            (126, 'Greenland', 'Greenland', 'gl', 'gl.svg'),
                                            (127, 'Grenada', 'Grenada', 'gd', 'gd.svg'),
                                            (128, 'Guadeloupe', 'Guadeloupe', 'gp', 'gp.svg'),
                                            (129, 'Guam', 'Guam', 'gu', 'gu.svg'),
                                            (130, 'Guatemala', 'Guatemala', 'gt', 'gt.svg'),
                                            (131, 'Guernsey', 'Guernsey', 'gg', 'gg.svg'),
                                            (132, 'Guinea', 'Guinea', 'gn', 'gn.svg'),
                                            (133, 'Guinea-Bissau', 'Guinea-Bissau', 'gw', 'gw.svg'),
                                            (134, 'Haiti', 'Haiti', 'ht', 'ht.svg'),
                                            (135, 'Heard Island and McD', 'Heard Island and McDonald Islands', 'hm', 'hm.svg'),
                                            (136, 'Holy See', 'Holy See', 'va', 'va.svg'),
                                            (137, 'Honduras', 'Honduras', 'hn', 'hn.svg'),
                                            (138, 'Hong Kong', 'Hong Kong', 'hk', 'hk.svg'),
                                            (139, 'Hungary', 'Hungary', 'hu', 'hu.svg'),
                                            (140, 'Iceland', 'Iceland', 'is', 'is.svg'),
                                            (141, 'India', 'India', 'in', '68ff3dd4b1c31.svg'),
                                            (142, 'Indonesia', 'Indonesia', 'id', 'id.svg'),
                                            (143, 'Iran', 'Iran', 'ir', 'ir.svg'),
                                            (144, 'Iraq', 'Iraq', 'iq', 'iq.svg'),
                                            (145, 'Ireland', 'Ireland', 'ie', '69d8a39d5276e.png'),
                                            (146, 'Israel', 'Israel', 'il', '6909a36f3c68d.jpg'),
                                            (147, 'Jersey', 'Jersey', 'je', 'je.svg'),
                                            (148, 'Jordan', 'Jordan', 'jo', '68ff401022b87.svg'),
                                            (149, 'Kazakhstan', 'Kazakhstan', 'kz', 'kz.svg'),
                                            (150, 'Kenya', 'Kenya', 'ke', 'ke.svg'),
                                            (151, 'Kerguelen Islands', 'Kerguelen Islands', 'xg', 'xg.svg'),
                                            (152, 'Kiribati', 'Kiribati', 'ki', 'ki.svg'),
                                            (153, 'Korea', 'Korea', 'kr', 'kr.svg'),
                                            (154, 'Kuwait', 'Kuwait', 'kw', 'kw.svg'),
                                            (155, 'Kyrgyzstan', 'Kyrgyzstan', 'kg', 'kg.svg'),
                                            (156, 'Lao People\'s Democra', 'Lao People\'s Democratic Republic', 'la', 'la.svg'),
                                            (157, 'Lebanon', 'Lebanon', 'lb', '68f203bb776c7.png'),
                                            (158, 'Lesotho', 'Lesotho', 'ls', 'ls.svg'),
                                            (159, 'Libya', 'Libya', 'ly', '68ff2d872ac61.svg'),
                                            (160, 'Liechtenstein', 'Liechtenstein', 'li', 'li.svg'),
                                            (161, 'Macao', 'Macao', 'mo', 'mo.svg'),
                                            (162, 'Macedonia (FYROM)', 'Macedonia (FYROM)', 'mk', 'mk.svg'),
                                            (163, 'Madagascar', 'Madagascar', 'mg', 'mg.svg'),
                                            (164, 'Madeira', 'Madeira', 'xb', 'xb.svg'),
                                            (165, 'Malawi', 'Malawi', 'mw', 'mw.svg'),
                                            (166, 'Maldives', 'Maldives', 'mv', 'mv.svg'),
                                            (167, 'Mali', 'Mali', 'ml', 'ml.svg'),
                                            (168, 'Martinique', 'Martinique', 'mq', 'mq.svg'),
                                            (169, 'Mauritania', 'Mauritania', 'mr', '68ff3e8b8d979.svg'),
                                            (170, 'Mauritius', 'Mauritius', 'mu', 'mu.svg'),
                                            (171, 'Mayotte', 'Mayotte', 'yt', 'yt.svg'),
                                            (172, 'Mexico', 'Mexico', 'mx', '6970b544a1349.svg'),
                                            (173, 'Micronesia', 'Micronesia', 'fm', 'fm.svg'),
                                            (174, 'Moldova', 'Moldova', 'md', 'md.svg'),
                                            (175, 'Monaco', 'Monaco', 'mc', 'mc.svg'),
                                            (176, 'Mongolia', 'Mongolia', 'mn', 'mn.svg'),
                                            (177, 'Montenegro', 'Montenegro', 'me', '6909a58cd5838.png'),
                                            (178, 'Montserrat', 'Montserrat', 'ms', 'ms.svg'),
                                            (179, 'Marocco', 'Morocco', 'ma', '68eca2f607ce1.png'),
                                            (180, 'Mozambique', 'Mozambique', 'mz', 'mz.svg'),
                                            (181, 'Myanmar', 'Myanmar', 'mm', 'mm.svg'),
                                            (182, 'Namibia', 'Namibia', 'na', 'na.svg'),
                                            (183, 'Nauru', 'Nauru', 'nr', 'nr.svg'),
                                            (184, 'Nepal', 'Nepal', 'np', 'np.svg'),
                                            (185, 'Netherlands Antilles', 'Netherlands Antilles', 'an', 'an.svg'),
                                            (186, 'New Caledonia', 'New Caledonia', 'nc', 'nc.svg'),
                                            (187, 'Nicaragua', 'Nicaragua', 'ni', 'ni.svg'),
                                            (188, 'Niger', 'Niger', 'ne', 'ne.svg'),
                                            (189, 'Nigeria', 'Nigeria', 'ng', '68ff3f8d0a2b4.jpg'),
                                            (190, 'Niue', 'Niue', 'nu', 'nu.svg'),
                                            (191, 'Norfolk Island', 'Norfolk Island', 'nf', 'nf.svg'),
                                            (192, 'North Korea', 'North Korea', 'kp', 'kp.svg'),
                                            (193, 'Northern Mariana Isl', 'Northern Mariana Islands', 'mp', 'mp.svg'),
                                            (194, 'Norway', 'Norway', 'no', '690b4d063bb4a.png'),
                                            (195, 'Oman', 'Oman', 'om', 'om.svg'),
                                            (196, 'Pakistan', 'Pakistan', 'pk', 'pk.svg'),
                                            (197, 'Palau', 'Palau', 'pw', 'pw.svg'),
                                            (198, 'Palestine', 'Palestine', 'ps', 'ps.svg'),
                                            (199, 'Papua New Guinea', 'Papua New Guinea', 'pg', 'pg.svg'),
                                            (200, 'Paraguay', 'Paraguay', 'py', 'py.svg'),
                                            (201, 'Peru', 'Peru', 'pe', 'pe.svg'),
                                            (202, 'Philippines', 'Philippines', 'ph', 'ph.svg'),
                                            (203, 'Pitcairn', 'Pitcairn', 'pn', 'pn.svg'),
                                            (204, 'Puerto Rico', 'Puerto Rico', 'pr', 'pr.svg'),
                                            (205, 'Qatar', 'Qatar', 'qa', 'qa.svg'),
                                            (206, 'Reunion', 'Reunion', 're', 're.svg'),
                                            (207, 'Romania', 'Romania', 'ro', 'ro.svg'),
                                            (208, 'Russian Federation', 'Russian Federation', 'ru', '6909a3f5bb30f.svg'),
                                            (209, 'Rwanda', 'Rwanda', 'rw', 'rw.svg'),
                                            (210, 'Saint Barthelemy', 'Saint Barthelemy', 'bl', 'bl.svg'),
                                            (211, 'Saint Helena, Ascens', 'Saint Helena, Ascension and Tristan da Cunha', 'sh', 'sh.svg'),
                                            (212, 'Saint Kitts and Nevi', 'Saint Kitts and Nevis', 'kn', 'kn.svg'),
                                            (213, 'Saint Lucia', 'Saint Lucia', 'lc', 'lc.svg'),
                                            (214, 'Saint Martin (FR)', 'Saint Martin (FR)', 'mf', 'mf.svg'),
                                            (215, 'Saint Paul and Amste', 'Saint Paul and Amsterdam Islands', 'xi', 'xi.svg'),
                                            (216, 'Saint Pierre and Miq', 'Saint Pierre and Miquelon', 'pm', 'pm.svg'),
                                            (218, 'Samoa', 'Samoa', 'ws', 'ws.svg'),
                                            (220, 'Sao Tome and Princip', 'Sao Tome and Principe', 'st', 'st.svg'),
                                            (221, 'Saudi Arabia', 'Saudi Arabia', 'sa', '68ff2bea4e615.svg'),
                                            (222, 'Senegal', 'Senegal', 'sn', '68ff3fd137257.svg'),
                                            (223, 'Serbia', 'Serbia', 'rs', 'rs.svg'),
                                            (224, 'Seychelles', 'Seychelles', 'sc', 'sc.svg'),
                                            (225, 'Sierra Leone', 'Sierra Leone', 'sl', 'sl.svg'),
                                            (226, 'Sint Maarten (NL)', 'Sint Maarten (NL)', 'sx', 'sx.svg'),
                                            (227, 'Slovakia', 'Slovakia', 'sk', 'sk.svg'),
                                            (228, 'Slovenia', 'Slovenia', 'si', '6909a4dac693c.svg'),
                                            (229, 'Solomon Islands', 'Solomon Islands', 'sb', 'sb.svg'),
                                            (230, 'Somalia', 'Somalia', 'so', 'so.svg'),
                                            (232, 'South Georgia', 'South Georgia', 'gs', 'gs.svg'),
                                            (233, 'South Sudan', 'South Sudan', 'ss', 'ss.svg'),
                                            (235, 'Sudan', 'Sudan', 'sd', 'sd.svg'),
                                            (236, 'Suriname', 'Suriname', 'sr', 'sr.svg'),
                                            (237, 'Svalbard and Jan May', 'Svalbard and Jan Mayen', 'sj', 'sj.svg'),
                                            (238, 'Swaziland', 'Swaziland', 'sz', 'sz.svg'),
                                            (239, 'Sweden', 'Sweden', 'se', 'se.svg'),
                                            (240, 'Switzerland', 'Switzerland', 'ch', 'ch.svg'),
                                            (241, 'Syrian Arab Republic', 'Syrian Arab Republic', 'sy', '68ff2b0d368dc.webp'),
                                            (242, 'Tahiti', 'Tahiti', 'xh', 'xh.svg'),
                                            (243, 'Taiwan (Province of ', 'Taiwan (Province of China)', 'tw', 'tw.svg'),
                                            (244, 'Tajikistan', 'Tajikistan', 'tj', 'tj.svg'),
                                            (245, 'Tanzania', 'Tanzania', 'tz', 'tz.svg'),
                                            (246, 'Thailand', 'Thailand', 'th', 'th.svg'),
                                            (247, 'Togo', 'Togo', 'tg', 'tg.svg'),
                                            (248, 'Tokelau', 'Tokelau', 'tk', 'tk.svg'),
                                            (249, 'Tonga', 'Tonga', 'to', 'to.svg'),
                                            (250, 'Trinidad and Tobago', 'Trinidad and Tobago', 'tt', 'tt.svg'),
                                            (251, 'Tunisia', 'Tunisia', 'tn', '6909a5c5203d0.svg'),
                                            (252, 'Turkmenistan', 'Turkmenistan', 'tm', 'tm.svg'),
                                            (253, 'Turks and Caicos Isl', 'Turks and Caicos Islands', 'tc', 'tc.svg'),
                                            (254, 'Tuvalu', 'Tuvalu', 'tv', 'tv.svg'),
                                            (255, 'Uganda', 'Uganda', 'ug', 'ug.svg'),
                                            (256, 'Ukraine', 'Ukraine', 'ua', '6909a362df670.webp'),
                                            (257, 'United Arab Emirates', 'United Arab Emirates', 'ae', 'ae.svg'),
                                            (258, 'United States Minor ', 'United States Minor Outlying Islands', 'um', 'um.svg'),
                                            (259, 'USA', 'United States of America', 'us', '68ff2d4a0c8e6.svg'),
                                            (260, 'Unknown', 'Unknown', 'xx', 'xx.svg'),
                                            (261, 'Uruguay', 'Uruguay', 'uy', 'uy.svg'),
                                            (262, 'Uzbekistan', 'Uzbekistan', 'uz', 'uz.svg'),
                                            (263, 'Vanuatu', 'Vanuatu', 'vu', 'vu.svg'),
                                            (264, 'Venezuela', 'Venezuela', 've', 've.svg'),
                                            (266, 'Virgin Islands (GB)', 'Virgin Islands (GB)', 'vg', 'vg.svg'),
                                            (267, 'Virgin Islands (US)', 'Virgin Islands (US)', 'vi', 'vi.svg'),
                                            (268, 'Wallis and Futuna', 'Wallis and Futuna', 'wf', 'wf.svg'),
                                            (269, 'Western Sahara', 'Western Sahara', 'eh', 'eh.svg'),
                                            (270, 'Yemen', 'Yemen', 'ye', 'ye.svg'),
                                            (271, 'Yugoslavia', 'Yugoslavia', 'yu', 'yu.svg'),
                                            (272, 'Zambia', 'Zambia', 'zm', 'zm.svg'),
                                            (273, 'Zimbabwe', 'Zimbabwe', 'zw', 'zw.svg');" );
    }

    public function down( Schema $schema ): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    }
}
